server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      format_sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root

  sql:
    init:
      mode: always
