drop table IF EXISTS stats;

create TABLE IF NOT EXISTS stats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        VARCHAR(200)                            NOT NULL,
    uri        VARCHAR(2000)                           NOT NULL,
    ip         VARCHAR                                 NOT NULL,
    timestamp  TIMESTAMP,
    CONSTRAINT pk_states PRIMARY KEY (id)
);