drop table IF EXISTS endpoint_hit;

create TABLE IF NOT EXISTS endpoint_hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(200)                            NOT NULL,
    uri       VARCHAR(200)                            NOT NULL,
    ip        VARCHAR(200)                            NOT NULL,
    timestamp TIMESTAMP,
    CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);